dist: trusty
sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
  - "./node_modules"
node_js:
- 8.11.1
install:
- npm install
script:
- npm run ci
deploy:
  provider: heroku
  api_key:
    secure: FEeCjm0W5bfLVMmxDe1aLvlEmFG7dLhD93+iu0ZMvEfxZUpuXhUfvsgFvGqt0i2MpwazoOPLPy0niFD/IYGY/8Vx63vKuFHNCngNv6YTcaie+uVdw0JlG6WqVD6ixTeQ1nieesKgqmXU7R8YttyrGmUQTJ2x351CHXWYqNMps1fECktE8stVvM4p1juI9+YnyGtZBmEErYuXG3qAsi3yxODMosZrP0JP0mEFaC5sir95tbwoFqbnuY6lmy+aZ9FyNI6Asixfu12ZfcsLmIM0VXj4dYTaTTknGazwNxnmng1E1nU4JCItA/6GXExUfI0bTTXSI0OdMn0LZRuakkyXTpEw68GNGyFVjN4b533IZ28fZRC1OIPW8xytHIhYLcNg4EmsRClTTCLR2evAZfNGVOHY77LqNLBPOHgjZ9ZvHBeJbaR5tW3ZYESbBviWPVoJ7xZ9UMT8NchLeKVycQnLfaYnGDrvq4VQv9Pukq+bjABM++ZU8cAxpXQI3QYNxAMsDpNaIjYc/5fatf39u4X9L06lNmnQDbb4gd1SxaC+HghemKMDWStS/Qv25co9E1IIL3xYSOL9vlFkE5DFTVBld3ELLOEtmTJgr7NrvIryfLGHsjES9w72PbmxobITU21GzNiQUvoSRtPZjCh8pAcc4VO6tUCKbijA3G1YyyOyF28=
  skip_cleanup: true
  app: chaptr
  on:
    repo: devCrossNet/chaptr
